### ISSUE TITLE
Github workflow tests show passing even thought they have failures.

### ISSUE THREAD

**Issue by vegu** [fullctl/aaactl#10]
see https://github.com/fullctl/aaactl/runs/1904343091?check_suite_focus=true#step:6:81

**Comment by egfrank** [comment]
I think the way we're running Docker is probably swallowing the exit code of the pytest output:
[this](https://stackoverflow.com/questions/46300610/how-to-get-the-numeric-exit-status-of-an-exited-docker-container) seems relevant

**Comment by egfrank** [comment]
@vegu I'm pretty sure for this change it's just enough to remove the command that was happening after `pytest` in the `entrypoint.sh` file.
https://github.com/fullctl/aaactl/compare/gh_10

Once the tests pass we can evaluate if that `coverage` command was necessary - I think it's currently covered in the pytest command and therefore was redundant (in addition to messing up the exit code)

I copied that change to `gh_8` if you'd like to just merge that branch for both issues

**Comment by egfrank** [comment]
Awesome, pushed changes so now the tests are all passing @vegu 

https://github.com/fullctl/aaactl/actions/runs/577018796
