### ISSUE TITLE
Github workflow for linting (flake8, black, isort) and testing

### ISSUE THREAD

**Issue by vegu** [fullctl/aaactl#4]
Github workflow for linting (`flake8`, `black`, `isort`) and testing, can look [here](https://github.com/20c/ctl/blob/master/.github/workflows/tests.yml) for an example.

Also fix `flake8` issues if there are any. Lets discuss things like "function too complex" prior to implementation changes though.

Failing unit tests can be ignored for the scope of this, we will tackle those separately.

**Comment by egfrank** [comment]
Just noting that it seems like the billing tests are all failing with the error `ValueError: Cannot assign "'test'": "Product.component" must be a "Service" instance` (happens in the fixtures)

**Comment by egfrank** [comment]
I'm going to hold off on making all the flake8 changes to billing until I get clarity on the tests, since I don't want to make a ton of changes if I'm not able to test. cc: @vegu

**Comment by egfrank** [comment]
Here's the Pull Request: https://github.com/fullctl/aaactl/pull/5
