### ISSUE TITLE
Bring over ledger changes from gitlab

### ISSUE THREAD

**Issue by vegu** [fullctl/aaactl#8]
They are currently still in a merge request there

Should be done after #2 and #3

**Comment by egfrank** [comment]
Just for reference here is the Gitlab PR: https://git.20c.com/gh/fullctl/aaactl/-/merge_requests/2/diffs#04c19c7aaed5af93afe31ce50934e49798780ba7

**Comment by egfrank** [comment]
Hi @vegu those changes are in this PR here:
https://github.com/fullctl/aaactl/pull/11

Note that that PR also can be used to close https://github.com/fullctl/aaactl/issues/10 if you'd like
